#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_godot_ide = env_modules.Clone()

# Add source files
env.add_source_files(env.modules_sources, "*.cpp")
